# Site settings
title: Bryans Place
author:
  name: Bryan
# description appears in footer
#description: "Great site !"

# Build settings
#remote_theme: jekyll/minima
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme